image: postgres:17

secrets:
  POSTGRES_DB: {}
  POSTGRES_PASSWORD: {}
  POSTGRES_USER: {}
env:
  PGDATA: "/var/lib/postgresql/data/pgdata"
resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "200Gi"
    cpu: "100m"
  storage: 1Gi

ports:
  port: 5432

env:
  secretName: data-service-postgres-secrets