replicaCount: 1
image:
  repository: ghcr.io/semantic-hallucinations/uma-event-storage
  tag: main-2025-12-21-15h52m
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
env:
  secretName: uma-event-storage-secrets
