apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-headless
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.ports.port }}
      name: {{ .Values.ports.name }}
  selector:
    app: {{ .Release.Name }}