apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  ports:
    - port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.port }}
  selector:
    app: {{ .Release.Name }}