apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort:  {{ .Values.service.targetPort | default 80 }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
