replicaCount: 1
image:
  repository: ghcr.io/semantic-hallucinations/uma-mcp-server
  tag: main-2025-12-21-15h41m
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
env:
  REDIS_HOST: data-service-redis-service
  REDIS_PORT: 6379
  REDIS_SCHEDULE_CACHE_TTL: 600
  REDIS_CURR_WEEK_CACHE_TTL: 5000
  secretName: uma-mcp-server-secrets
