replicaCount: 1

image:
  repository: semantic-hallucinations/uma-etl-crawler
  tag: main-2025-12-07-20h28m
  pullPolicy: IfNotPresent

env:
  LOG_LEVEL: "info"
  API_URL: "https://api.prod.example.com"

secretName: uma-etl-crawler-secrets
