apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql-service
spec:
  selector:
    app: {{ .Release.Name }}-postgresql
  ports:
      - port: {{ .Values.psqlService.port }}
        targetPort: {{ .Values.psqlService.targetPort }}
        protocol: TCP

