replicaCount: 1

image:
  repository: ghcr.io/semantic-hallucinations/uma-telegram-client
  tag: main-2025-12-07-20h28m
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  LOG_LEVEL: "info"
  API_URL: "https://api.prod.example.com"

secretName: uma-telegram-client-secrets
